const futureExchanges = [
    {
        code: 'CCFX',
        name: '中国金融期货交易所',
    },
    {
        code: 'GFEX',
        name: '广州期货交易所',
    },
    {
        code: 'XDCE',
        name: '大连商品交易所',
    },
    {
        code: 'XINE',
        name: '上海国际能源交易中心',
    },
    {
        code: 'XSGE',
        name: '上海期货交易所',
    },
    {
        code: 'XZCE',
        name: '郑州商品交易所',
    }
]

const futureExchangeProducts = [
    {
        key: '1',
        code: 'A',
        name: '豆一',
        exchange: 'XDCE',
    },
    {
        key: '2',
        code: 'B',
        name: '豆二',
        exchange: 'XDCE',
        subItems: [
            {
                key: '20001',
                code: 'B0503',
                name: '豆二B0503合约'
            },
            {
                key: '20002',
                code: 'B0505',
                name: '豆二B0505合约'
            },
            {
                key: '20003',
                code: 'B0507',
                name: '豆二B0507合约'
            },
        ]
    },
    {
        key: '3',
        code: 'BB',
        name: '胶合板',
        exchange: 'XDCE',
    },
    {
        key: '4',
        code: 'C',
        name: '玉米',
        exchange: 'XDCE',
    },
    {
        key: '5',
        code: 'CS',
        name: '淀粉',
        exchange: 'XDCE',
    },
    {
        key: '6',
        code: 'EB',
        name: '苯乙烯',
        exchange: 'XDCE',
    },
    {
        key: '7',
        code: 'EG',
        name: '乙二醇',
        exchange: 'XDCE',
    },
    {
        key: '8',
        code: 'FB',
        name: '纤维板',
        exchange: 'XDCE',
    },
    {
        key: '9',
        code: 'I',
        name: '铁矿石',
        exchange: 'XDCE',
    },
    {
        key: '10',
        code: 'J',
        name: '焦炭',
        exchange: 'XDCE',
    },
    {
        key: '11',
        code: 'JD',
        name: '鸡蛋',
        exchange: 'XDCE',
    },
    {
        key: '12',
        code: 'JM',
        name: '焦煤',
        exchange: 'XDCE',
    },
    {
        key: '13',
        code: 'L',
        name: '塑料',
        exchange: 'XDCE',
    },
    {
        key: '14',
        code: 'M',
        name: '豆粕',
        exchange: 'XDCE',
    },
    {
        key: '15',
        code: 'LH',
        name: '生猪',
    },
    {
        key: '16',
        code: 'P',
        name: '棕榈油',
        exchange: 'XDCE',
    },
    {
        key: '17',
        code: 'PP',
        name: '聚丙烯',
        exchange: 'XDCE',
    },
    {
        key: '18',
        code: 'PG',
        name: '液化石油气',
        exchange: 'XDCE',
    },
    {
        key: '19',
        code: 'RR',
        name: '粳米',
        exchange: 'XDCE',
    },
    {
        key: '20',
        code: 'V',
        name: 'PVC',
        exchange: 'XDCE',
    },
    {
        key: '21',
        code: 'Y',
        name: '豆油',
        exchange: 'XDCE',
    },
    {
        key: '22',
        code: 'AP',
        name: '苹果',
        exchange: 'XZCE',
    },
    {
        key: '23',
        code: 'CF',
        name: '棉花',
        exchange: 'XZCE',
    },
    {
        key: '24',
        code: 'CJ',
        name: '红枣',
        exchange: 'XZCE',
    },
    {
        key: '25',
        code: 'CY',
        name: '棉纱',
        exchange: 'XZCE',
    },
    {
        key: '26',
        code: 'ER',
        name: '早籼稻',
        exchange: 'XZCE',
    },
    {
        key: '27',
        code: 'FG',
        name: '玻璃',
        exchange: 'XZCE',
    },
    {
        key: '28',
        code: 'GN',
        name: '锰硅',
        exchange: 'XZCE',
    },
    {
        key: '29',
        code: 'JR',
        name: '粳稻',
        exchange: 'XZCE',
    },
    {
        key: '30',
        code: 'LR',
        name: '晚籼稻',
        exchange: 'XZCE',
    },
    {
        key: '31',
        code: 'MA',
        name: '甲醇',
        exchange: 'XZCE',
    },
    {
        key: '32',
        code: 'ME',
        name: '甲醇',
        exchange: 'XZCE',
    },
    {
        key: '33',
        code: 'OI',
        name: '菜籽油',
        exchange: 'XZCE',
    },
    {
        key: '34',
        code: 'PM',
        name: '普麦',
        exchange: 'XZCE',
    },
    {
        key: '35',
        code: 'PF',
        name: '短纤',
        exchange: 'XZCE',
    },
    {
        key: '36',
        code: 'PK',
        name: '花生',
        exchange: 'XZCE',
    },
    {
        key: '37',
        code: 'RI',
        name: '早籼稻',
        exchange: 'XZCE',
    },
    {
        key: '38',
        code: 'RM',
        name: '菜籽粕',
        exchange: 'XZCE',
    },
    {
        key: '39',
        code: 'RS',
        name: '菜籽油',
        exchange: 'XZCE',
    },
    {
        key: '40',
        code: 'RO',
        name: '菜籽油',
        exchange: 'XZCE',
    },
    {
        key: '41',
        code: 'SA',
        name: '纯碱',
        exchange: 'XZCE',
    },
    {
        key: '42',
        code: 'SF',
        name: '硅铁',
        exchange: 'XZCE',
    },
    {
        key: '43',
        code: 'SM',
        name: '锰硅',
        exchange: 'XZCE',
    },
    {
        key: '44',
        code: 'SR',
        name: '白糖',
        exchange: 'XZCE',
    },
    {
        key: '45',
        code: 'TA',
        name: 'PTA',
        exchange: 'XZCE',
    },
    {
        key: '46',
        code: 'TC',
        name: '动力煤',
        exchange: 'XZCE',
    },
    {
        key: '47',
        code: 'UR',
        name: '尿素',
        exchange: 'XZCE',
    },
    {
        key: '48',
        code: 'WH',
        name: '强麦',
        exchange: 'XZCE',
    },
    {
        key: '49',
        code: 'WS',
        name: '强麦',
        exchange: 'XZCE',
    },
    {
        key: '50',
        code: 'WT',
        name: '硬麦',
        exchange: 'XZCE',
    },
    {
        key: '51',
        code: 'ZC',
        name: '动力煤',
        exchange: 'XZCE',
    },
    {
        key: '52',
        code: 'IC',
        name: '中证500指数',
        exchange: 'CCFX',
    },
    {
        key: '53',
        code: 'IF',
        name: '沪深300指数',
        exchange: 'CCFX',
    },
    {
        key: '54',
        code: 'IH',
        name: '上证50指数',
        exchange: 'CCFX',
    },
    {
        key: '55',
        code: 'T',
        name: '10年期国债',
        exchange: 'CCFX',
    },
    {
        key: '56',
        code: 'IM',
        name: '1月国债',
        exchange: 'CCFX',
    },
    {
        key: '57',
        code: 'TF',
        name: '5年期国债',
        exchange: 'CCFX',
    },
    {
        key: '58',
        code: 'TS',
        name: '2年期国债',
        exchange: 'CCFX',
    },
    {
        key: '59',
        code: 'TL',
        name: '3年期国债',
        exchange: 'CCFX',
    },
    {
        key: '60',
        code: 'SI',
        name: '工业硅',
        exchange: 'GFEX',
    },
    {
        key: '61',
        code: 'BC',
        name: '国际铜',
        exchange: 'XINE',
    },
    {
        key: '62',
        code: 'LU',
        name: '低硫燃料油',
        exchange: 'XINE',
    },
    {
        key: '63',
        code: 'SC',
        name: '原油',
        exchange: 'XINE',
    },
    {
        key: '64',
        code: 'NR',
        name: '20号胶',
        exchange: 'XINE',
    },
    {
        key: '65',
        code: 'AG',
        name: '白银',
        exchange: 'XSGE',
    },
    {
        key: '66',
        code: 'AL',
        name: '铝',
        exchange: 'XSGE',
    },
    {
        key: '67',
        code: 'AO',
        name: '菜籽油',
        exchange: 'XSGE',
    },
    {
        key: '68',
        code: 'AU',
        name: '黄金',
        exchange: 'XSGE',
    },
    {
        key: '69',
        code: 'BU',
        name: '沥青',
        exchange: 'XSGE',
    },
    {
        key: '70',
        code: 'CU',
        name: '铜',
        exchange: 'XSGE',
    },
    {
        key: '71',
        code: 'FU',
        name: '燃料油',
        exchange: 'XSGE',
    },
    {
        key: '72',
        code: 'HC',
        name: '热轧卷板',
        exchange: 'XSGE',
    },
    {
        key: '73',
        code: 'NI',
        name: '镍',
        exchange: 'XSGE',
    },
    {
        key: '74',
        code: 'PB',
        name: '铅',
        exchange: 'XSGE',
    },
    {
        key: '75',
        code: 'RB',
        name: '螺纹钢',
        exchange: 'XSGE',
    },
    {
        key: '76',
        code: 'RU',
        name: '天然橡胶',
        exchange: 'XSGE',
    },
    {
        key: '77',
        code: 'SN',
        name: '锡',
        exchange: 'XSGE',
    },
    {
        key: '78',
        code: 'SP',
        name: '纸浆',
        exchange: 'XSGE',
    },
    {
        key: '79',
        code: 'SS',
        name: '不锈钢',
        exchange: 'XSGE',
    },
    {
        key: '80',
        code: 'WR',
        name: '线材',
        exchange: 'XSGE',
    },
    {
        key: '81',
        code: 'ZN',
        name: '锌',
        exchange: 'XSGE',
    }
]

module.exports = {
    futureExchanges,
    futureExchangeProducts
}